### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by t0mk** [t0mk/ansible-collection-equinix#4]
Existing modules:
- [x] metal_project
- [x] metal_project_info
- [x] metal_device
- [x] metal_device info

The modules look resourcs up by id or name (or hostname in case of device). The _info modules can use `filter` argument for API lookup, for example 
```yaml:
metal_device_info:
  project_id: 173d7f11-f7b9-433e-ac40-f1571a38037a
  filters:
    hostname: mydev
```
.. will issue API call `/projects/173d7f11-f7b9-433e-ac40-f1571a38037a/devices?hostname=mydev`

The documentation of the modules is in good shape but could be better, especially RETURNS field.

Modules to come:
- [ ] ip addresses
- [ ] ssh keys
